name: run sql queries

on:
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  process_all_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install jq (Global for all runs)
      run: |
        set -eo pipefail # Apply to this setup step as well
        # Install jq (JSON processor for shell scripting)
        echo "Installing jq..."
        sudo apt-get update && sudo apt-get install -y jq
        jq --version
      shell: bash

    - name: run sql queries from files
      run: |
        echo "Running buildcats.sql"
        sqlite3 data.db < sql-query/buildcats.sql | jq '.[] |= with_entries(.value |= (fromjson? // .))' > sql-query/result/buildcats.json

        echo "Running latest100.sql"
        sqlite3 data.db < sql-query/latest100.sql | jq '.[] |= with_entries(.value |= (fromjson? // .))' > sql-query/result/latest100.json

    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add '*.json'
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
